<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cli</string>
		<string>kleio</string>
		<string>rpt</string>
		<string>CLI</string>
		<string>KLEIO</string>
		<string>org</string>
		<string>old</string>
	</array>
	<key>name</key>
	<string>Kleio</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([a-z][a-z0-9\.-]*)(\$)([A-z0-9 \.-]*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[^#\$%]*(/)([a-z][a-z0-9\.-]*)\=</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*[^#\/\$#%]*$</string>
			<key>name</key>
			<string>text</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^WARNING\:.*</string>
			<key>name</key>
			<string>invalid.deprecated</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[0-9]*\s\swarnings\.</string>
			<key>name</key>
			<string>invalid.deprecated</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^ERROR\:.*</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[0-9]*\s\serrors\.</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\*\*\s.*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[^0-9].*</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.constant</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[0-9]+\:\s*([a-z][a-z0-9\.-]*)(\$)([a-z0-9\.-]*)(/)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([a-z][a-z0-9\.-]*)(\$)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[0-9]+\:\s*([a-z][a-z0-9\.-]*)(\$)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other.constant</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(/)(id|mesmo_que|xmesmo_que|same_as|xsame_as)(=)([a-z0-9\.-]*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(/)([a-z][a-z0-9\.-]*)\=</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.original</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(%)([^\/]*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.note</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)([^\/%]*)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/</string>
			<key>name</key>
			<string>punctuation.separator</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kleio</string>
	<key>uuid</key>
	<string>6F8B6291-02B6-416D-A77D-5068951073C2</string>
</dict>
</plist>
